# Basic configurations on CDD dataset

# Data
dataset: CDD
num_workers: 1
repeats: 1
subset: val
crop_size: 256


# Optimizer
optimizer: Adam
lr: 0.0004
weight_decay: 0.0
load_optim: False
save_optim: False
sched_on: True
schedulers:
  - name: StepLR
    step_size: 70
    gamma: 0.1


# Training related
batch_size: 8
num_epochs: 200
resume: ''
anew: False
device: cuda
channel: 3

# Experiment
exp_dir: ../exp/
# tag: ''
# suffix: ''
# DO NOT specify exp_config
debug_on: False
inherit_off: False
log_off: False
track_intvl: 10
tb_on: False
tb_intvl: 500
suffix_off: True
save_on: False
out_dir: ''


# Criterion
criterion: WNLL
weights: 
  - 0.5   # Weight of no-change class
  - 0.5   # Weight of change class


# Model
model: 
out_type: logits2
